import './globals.css';
import Header from './layouts/Header';
import Footer from './layouts/Footer';
import { Inter, Roboto_Mono } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
  display: 'swap',
});

const robotoMono = Roboto_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  icons: {
    icon: 'image/favicon.ico', 
  },
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body className="antialiased" suppressHydrationWarning={true}>

        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
